spring.application.name=proyectos
spring.datasource.url=jdbc:postgresql://localhost:5432/proyectos_db
spring.datasource.username=postgres
spring.datasource.password=BeckerC2005


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085

logging.level.org.springframework.security=DEBUG